### ISSUE TITLE
Implement (co-zeus) / Logi / PLTMED / Eng

### ISSUE THREAD

**Issue by BratwurstAngel** [tomseli/BWI-Templates#34]
Implement (co-zeus) / Logi / PLTMED / Eng,

**Comment by tomseli** [comment]
- [x] add loadout for Logi / Medic / Eng as well

**Comment by tomseli** [comment]
Callsign: Logistics
Add to own group 

Radio:
117: PLNET
152: CMDNET

**Comment by tomseli** [comment]
Logistics has been added as a playable role. They have a specific loadout and should have permissions to be both an engineer and medic. Furthermore, the radios should automatically configure.

Note on the loadout:
Carrying a toolkit + a surgical kit + 117 leaves very little volumetric room in the kit, weight is fine.
To mitigate this, they carry less ammo (-2 magazines) and carry a minimal medical kit. Either of these things shouldn't be an issue as logistics has access to all resupply.
