### ISSUE TITLE
Add an Australian Loadout to the templates

### ISSUE THREAD

**Issue by tomseli** [tomseli/BWI-Templates#49]
Required information as listed below. 

## Loadouts
Please make a separate comment per loadout.

Expected format: ACE arsenal export.

- [x] Automatic Rifleman
- [x] Combat First Responder
- [x] Grenadier
- [x] Logistics
- [x] Medium anti-tank gunner
- [x] Medium anti-tank leader
- [x] Medium machine gun gunner
- [x] Medium machine gun leader
- [x] Platoon leader
- [x] Rifleman
- [x] Squad Leader

## Miscellaneous items
All items that are NOT added to any of the loadouts e.g., demo charges or spray paint.
See `BWI_Tembelan.Tembelan/data/miscellaneous.sqf` for an example.

Expected format: A comma separated list of strings (names must exactly match, case sensitive) e.g., 
`["item1", "item2", "item3"]`

## Attachments
All attachments that should be added to the arsenal are listed here.
See `BWI_Tembelan.Tembelan/data/attachments.sqf` for an example.

Expected format: A comma separated list of strings (names must exactly match, case sensitive) e.g., 
`["attachment1", "attachment2", "attachment3"]`

**Comment by Sentinel739** [comment]
Automatic Rifleman

[[["rhs_weap_m249","","","",["rhsusf_200Rnd_556x45_M855_mixed_soft_pouch_coyote",200],[],"rhsusf_acc_saw_bipod"],[],["UK3CB_USP","","","",["UK3CB_USP_9_15Rnd",15],[],""],["AUSPAT_G3L_AMCU_AMCU_Camo",[["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACE_packingBandage",5],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_splint",2],["ACRE_PRC343",1]]],["AUSPAT_CarrierLite_AMCU",[["rhsusf_200Rnd_556x45_M855_mixed_soft_pouch",2,200]]],["AUSPAT_Tactical_AMCU",[["rhsusf_200Rnd_556x45_M855_mixed_soft_pouch",2,200]]],"AUSPAT_FAST_02_AMCU","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]],[]]

**Comment by Sentinel739** [comment]
CFR

[[["uk3cb_auga3_blk","","","",["UK3CB_AUG_30Rnd_556x45_Magazine",30],[],""],[],["UK3CB_USP","","","",["UK3CB_USP_9_15Rnd",15],[],""],["AUSPAT_G3L_AMCU_AMCU_Camo",[["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACE_packingBandage",6],["ACE_tourniquet",6],["ACE_microDAGR",1],["ACRE_PRC343",1]]],["AUSPAT_MMAC_Belt_Med_AMCU",[["rhs_mag_m67",2,1],["UK3CB_USP_9_15Rnd",2,15],["UK3CB_AUG_30Rnd_556x45_Magazine_R",8,30]]],["AUSPAT_Tactical_AMCU",[["ACE_elasticBandage",20],["ACE_packingBandage",20],["ACE_quikclot",20],["ACE_bloodIV",4],["ACE_bloodIV_250",8],["ACE_bloodIV_500",8],["ACE_epinephrine",10],["ACE_morphine",6],["ACE_splint",6],["ACE_surgicalKit",1],["rhs_mag_an_m8hc",2,1],["ACE_painkillers",4,10]]],"AUSPAT_FAST_02_AMCU","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]],[]]

**Comment by Sentinel739** [comment]
Grenadier

[[["uk3cb_auga3_gl_blk","","","",["UK3CB_AUG_30Rnd_556x45_Magazine_R",30],[],""],[],["UK3CB_USP","","","",["UK3CB_USP_9_15Rnd",15],[],""],["AUSPAT_G3L_AMCU_AMCU_Camo",[["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACE_packingBandage",5],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACRE_PRC343",1]]],["AUSPAT_CIRAS_Belt_Gren_AMCU",[["rhs_mag_m67",3,1],["rhs_mag_M441_HE",8,1],["UK3CB_AUG_30Rnd_556x45_Magazine_R",8,30],["UK3CB_USP_9_15Rnd",2,15]]],["AUSPAT_Tactical_AMCU",[["ACE_splint",2],["rhs_mag_an_m8hc",2,1],["rhs_mag_m714_White",4,1],["rhs_mag_m715_Green",2,1],["rhs_mag_m713_Red",2,1],["1Rnd_HE_Grenade_shell",8,1]]],"AUSPAT_FAST_02_AMCU","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]],[]]

**Comment by Sentinel739** [comment]
Logi

[[["uk3cb_auga3_blk","","","",["UK3CB_AUG_30Rnd_556x45_Magazine",30],[],""],[],["UK3CB_USP","","","",["UK3CB_USP_9_15Rnd",15],[],""],["AUSPAT_G3L_AMCU_AMCU_Camo",[["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACE_packingBandage",5],["ACE_tourniquet",2],["ACE_splint",2],["ACE_microDAGR",1],["ACRE_PRC152",1]]],["AUSPAT_CarrierLite_AMCU",[["ACE_elasticBandage",8],["ACE_packingBandage",8],["ACE_quikclot",8],["ACE_bloodIV_500",4],["ACE_bloodIV",2],["UK3CB_AUG_30Rnd_556x45_Magazine_R",8,30]]],["AUSPAT_Tactical_AMCU",[["ACE_surgicalKit",1],["ACE_epinephrine",5],["ACE_morphine",2],["ToolKit",1],["ACRE_PRC117F",1],["SmokeShell",2,1],["ACE_painkillers",2,10]]],"AUSPAT_FAST_02_AMCU","",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]],[]]

**Comment by Sentinel739** [comment]
MAT Gunner

[[["uk3cb_auga3_blk","","","",["UK3CB_AUG_30Rnd_556x45_Magazine",30],[],""],["rhs_weap_maaws","","","",[],[],""],[],["AUSPAT_G3L_AMCU_AMCU_Camo",[["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACE_packingBandage",5],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_splint",2],["ACRE_PRC343",1]]],["AUSPAT_CarrierLite_AMCU",[["UK3CB_AUG_30Rnd_556x45_Magazine_R",6,30]]],["AUSPAT_Tactical_AMCU",[["rhs_mag_maaws_HEAT",2,1]]],"AUSPAT_FAST_02_AMCU","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]],[]]

**Comment by Sentinel739** [comment]
MAT Lead

[[["uk3cb_auga3_blk","","","",["UK3CB_AUG_30Rnd_556x45_Magazine",30],[],""],[],["UK3CB_USP","","","",["UK3CB_USP_9_15Rnd",15],[],""],["AUSPAT_G3L_AMCU_AMCU_Camo",[["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACE_packingBandage",5],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_splint",2],["ACRE_PRC152",1],["ACRE_PRC343",1]]],["AUSPAT_CIRAS_Belt_TL_AMCU",[["rhs_mag_m67",1,1],["rhs_mag_an_m8hc",1,1],["UK3CB_USP_9_15Rnd",2,15],["UK3CB_AUG_30Rnd_556x45_Magazine_R",8,30]]],["AUSPAT_Tactical_AMCU",[["rhs_mag_maaws_HEAT",1,1],["rhs_mag_maaws_HEDP",1,1]]],"AUSPAT_FAST_02_AMCU","",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]],[]]

**Comment by Sentinel739** [comment]
MMG Gunner

[[["rhs_weap_m240G","","","",["rhsusf_100Rnd_762x51_m80a1epr",100],[],""],[],["UK3CB_USP","","","",["UK3CB_USP_9_15Rnd",15],[],""],["AUSPAT_G3L_AMCU_AMCU_Camo",[["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACE_packingBandage",5],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACRE_PRC343",1]]],["AUSPAT_CarrierLite_AMCU",[["UK3CB_USP_9_15Rnd",2,15],["rhsusf_100Rnd_762x51_m80a1epr",2,100]]],["AUSPAT_Tactical_AMCU",[["ACE_splint",2],["rhsusf_100Rnd_762x51_m80a1epr",2,100]]],"AUSPAT_FAST_02_AMCU","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]],[]]

**Comment by Sentinel739** [comment]
MMG Lead

[[["uk3cb_auga3_blk","","","",["UK3CB_AUG_30Rnd_556x45_Magazine",30],[],""],[],["UK3CB_USP","","","",["UK3CB_USP_9_15Rnd",15],[],""],["AUSPAT_G3L_AMCU_AMCU_Camo",[["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACE_packingBandage",5],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_splint",2],["ACRE_PRC152",1],["ACRE_PRC343",1]]],["AUSPAT_CIRAS_Belt_TL_AMCU",[["rhs_mag_m67",1,1],["rhs_mag_an_m8hc",1,1],["UK3CB_USP_9_15Rnd",2,15],["UK3CB_AUG_30Rnd_556x45_Magazine_R",8,30]]],["AUSPAT_Tactical_AMCU",[["rhsusf_100Rnd_762x51_m62_tracer",5,100],["ACE_SpareBarrel",2,1]]],"AUSPAT_FAST_02_AMCU","",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]],[]]

**Comment by Sentinel739** [comment]
PL

[[["uk3cb_auga3_blk","","","",["UK3CB_AUG_30Rnd_556x45_Magazine",30],[],""],[],["UK3CB_USP","","","",["UK3CB_USP_9_15Rnd",15],[],""],["AUSPAT_G3L_AMCU_AMCU_Camo",[["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACE_packingBandage",5],["ACE_tourniquet",2],["ACE_splint",2],["ACE_microDAGR",1],["ACRE_PRC152",1]]],["AUSPAT_CIRAS_Belt_TL_AMCU",[["rhs_mag_m67",2,1],["rhs_mag_an_m8hc",2,1],["SmokeShellGreen",1,1],["SmokeShellRed",1,1],["UK3CB_USP_9_15Rnd",2,15],["UK3CB_AUG_30Rnd_556x45_Magazine_R",8,30]]],["AUSPAT_Tactical_AMCU",[["ACRE_PRC117F",1]]],"AUSPAT_FAST_02_AMCU","",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]],[]]

**Comment by Sentinel739** [comment]
Rifleman

[[["uk3cb_auga3_blk","","","",["UK3CB_AUG_30Rnd_556x45_Magazine",30],[],""],["rhs_weap_m72a7","","","",[],[],""],[],["AUSPAT_G3L_AMCU_AMCU_Camo",[["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACE_packingBandage",5],["ACE_tourniquet",2],["ACE_splint",2],["ACE_microDAGR",1],["ACRE_PRC343",1]]],["AUSPAT_CarrierLite_AMCU",[["rhs_mag_m67",2,1],["UK3CB_AUG_30Rnd_556x45_Magazine_R",10,30]]],["AUSPAT_Tactical_AMCU",[["rhsusf_200Rnd_556x45_M855_mixed_soft_pouch",1,200]]],"AUSPAT_FAST_02_AMCU","",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]],[]]

**Comment by Sentinel739** [comment]
SL

[[["uk3cb_auga3_gl_blk","","","",["UK3CB_AUG_30Rnd_556x45_Magazine",30],[],""],[],["UK3CB_USP","","","",["UK3CB_USP_9_15Rnd",15],[],""],["AUSPAT_G3L_AMCU_AMCU_Camo",[["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACE_packingBandage",5],["ACE_tourniquet",2],["ACE_splint",2],["ACE_microDAGR",1],["ACRE_PRC152",1],["ACRE_PRC343",1]]],["AUSPAT_CIRAS_Belt_TL_AMCU",[["rhs_mag_m67",2,1],["rhs_mag_an_m8hc",2,1],["UK3CB_USP_9_15Rnd",2,15],["UK3CB_AUG_30Rnd_556x45_Magazine_R",8,30]]],["AUSPAT_Tactical_AMCU",[]],"AUSPAT_FAST_02_AMCU","",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]],[]]

**Comment by Sentinel739** [comment]
Mortar Lead

[[["uk3cb_auga3_gl_blk","","","",["UK3CB_AUG_30Rnd_556x45_Magazine",30],[],""],[],["UK3CB_USP","","","",["UK3CB_USP_9_15Rnd",15],[],""],["AUSPAT_G3L_AMCU_AMCU_Camo",[["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACE_packingBandage",5],["ACE_tourniquet",2],["ACE_splint",2],["ACE_microDAGR",1],["ACE_RangeTable_82mm",1],["ACE_Kestrel4500",1],["ACRE_PRC152",1],["ACRE_PRC343",1]]],["AUSPAT_CIRAS_Belt_TL_AMCU",[["rhs_mag_m67",2,1],["rhs_mag_an_m8hc",2,1],["UK3CB_USP_9_15Rnd",2,15],["UK3CB_AUG_30Rnd_556x45_Magazine_R",6,30]]],["I_E_Mortar_01_support_F",[]],"AUSPAT_FAST_02_AMCU","",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]],[]]

**Comment by Sentinel739** [comment]
Mortar gunner

[[["uk3cb_auga3_blk","","","",["UK3CB_AUG_30Rnd_556x45_Magazine",30],[],""],[],[],["AUSPAT_G3L_AMCU_AMCU_Camo",[["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACE_packingBandage",5],["ACE_tourniquet",2],["ACE_splint",2],["ACE_microDAGR",1],["ACRE_PRC343",1],["ACE_RangeTable_82mm",1],["ACE_Kestrel4500",1]]],["AUSPAT_CarrierLite_AMCU",[["rhs_mag_m67",2,1],["UK3CB_AUG_30Rnd_556x45_Magazine_R",6,30]]],["I_E_Mortar_01_Weapon_F",[]],"AUSPAT_FAST_02_AMCU","",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]],[]]
