### ISSUE TITLE
Fix 'Default Loadout' overwriting player faces/eye wear.

### ISSUE THREAD

**Issue by Volosz** [tomseli/BWI-Templates#50]
Faces and eye wear are overwritten by default load outs, making everyone look like Sentinel's avatar.

**Comment by tomseli** [comment]
I can't replicate my face being overwritten - neither the arsenal nor the default survivor overwrite my set profile face.

**Comment by Volosz** [comment]
Could not replicate anymore after update / new template. Recommend closing.
