### ISSUE TITLE
Respawning resets radio channels to different settings than default. 

### ISSUE THREAD

**Issue by BratwurstAngel** [tomseli/BWI-Templates#51]

**Comment by BratwurstAngel** [comment]
Multiple people reported radio's resetting their settings + resetting to different channels after respawning.

**Comment by tomseli** [comment]
Strange, I explicitly tested if it keeps the settings and it did. I'll put in a failsafe.

**Comment by tomseli** [comment]
I can't replicate the issue. Likely due to the lack of serverload. However, I implemented a fallback that should prevent it from happening again eitherway.
