### ISSUE TITLE
Teamspeak server spam protection

### ISSUE THREAD

**Issue by BratwurstAngel** [tomseli/BWI-Templates#53]
1.  Share the SSH keys (or get stabbed >:D 🗡️ )
2.  
Either: Bump up the spam limit 

OR implement user group excluded from the spam filter

Might be smart to just do both? 2-3 User groups? Admins - Users - Lesser trusted users?

**Comment by tomseli** [comment]
Implemented a member role. Angel and Volos have been promoted to admin to assign roles.
