### ISSUE TITLE
Sa'hatra respawn is bugged

### ISSUE THREAD

**Issue by tomseli** [tomseli/BWI-Templates#60]
Players respawn on body instead of at spawn

**Comment by tomseli** [comment]
Furthermore, there's reports of respawn breaking radio configs

**Comment by JonahReid** [comment]
Local MP
Reproduceability: happens every time.

I followed [this guide](https://steamcommunity.com/sharedfiles/filedetails/?id=629976492) to include an "Infantry Respawn" marker, call the variable name "respawn_west" and add "respawn = "BASE";" to the dsecription file.

I haven't found that death affects radios, but perhaps that's better to try on the server.

**Comment by JonahReid** [comment]
I see now from Tembelan that this is the same that was in use before, it just hasn't been moved over to Sa'hatra. So disregard my above comment, we don't need the "respawn = "BASE"; declaration.
![image](https://github.com/user-attachments/assets/0d5f3387-cf30-487b-95b1-956258b31bdd)
